# Architecture identifier.
arch = "riscv64"
# Platform identifier.
platform = "riscv64-starfive"
# Platform family.
family = "riscv64-starfive"

# Base address of the whole physical memory.
phys-memory-base = "0x8000_0000"
# Size of the whole physical memory.
phys-memory-size = "0x200_0000"     # 128M
# Base physical address of the kernel image.
kernel-base-paddr = "0x8020_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_ffc0_8020_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_ffc0_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0x16030000", "0x10000"],      # ethernet@0x16030000
    ["0x16040000", "0x10000"],      # ethernet@0x16040000


    ["0x8200_1000", "0x1000"],      # tdes
    ["0x8200_2000", "0x1000"],      # rdes

    ["0x8201_0000", "0x10000"],      # txbuffer
    ["0x8202_0000", "0x10000"],      # rxbuffer

    ["0x1981_0000", "0x10000"],      # clock-controller isp
    ["0x1302_0000", "0x10000"],      # clock-controller sys   4df0300
    ["0x1023_0000", "0x10000"],      # clock-controller stg   4e10000
    ["0x1700_0000", "0x10000"],      # clock-controller aon
    ["0x295c_0000", "0x10000"],      # clock-controller vout
    
    ["0x0201_0000", "0x1000"],       # cache_flush
    
    
    
]


# Timer interrupt frequency in Hz.
timer-frequency = "10_000_000"      # 10MHz
